### ISSUE TITLE
Internet explore open and nothing more

### ISSUE THREAD

**Issue by GiuseppeChillemi** [mmarcincin/HB-DRM-free-bulk-downloader#10]
Hi,
  I have dowloaded the new version and overwritten the old files. Now when I start the script internet explorer pop ups and nothing more happen in the powershell console.

**Comment by GiuseppeChillemi** [comment]
Just a note, download dir is: "\\?\R:\HB-START-HERE\downloads"
Is "\\?\" correct ? (Note: there are 2 "\" at the beginning but I don't know the scape character to show them)

**Comment by mmarcincin** [comment]
The path is ok, it's representation for 260+ length.
The IE shouldn't pop up unless the script file is modified, it's hidden window by default.
I just updated to 0.3.6 version today because of some other issues so you might try that one now.

**Comment by GiuseppeChillemi** [comment]
Have tried and it is working.
"Maybe" internet explorer popping up could be related to a humble bundle "purchases" link I have found in my bundles links.

**Comment by GiuseppeChillemi** [comment]
I have experimented and found the cause: "run.bat" must be executed with "run as administrator".

**Comment by mmarcincin** [comment]
Have you added https://www.humblebundle.com/ to trusted sites in IE and also enabled protected mode for them (disabled by default)?

**Comment by GiuseppeChillemi** [comment]
The protected mode was missing. Now it seems to work without starting the script as admin. Feel free to close the ticket if you have no further annotations.

**Comment by mmarcincin** [comment]
Without protected mode you get blank return for ie.ReadyState for some reason so you can't really work with Internet Explorer at all :).
