### ISSUE TITLE
Internet Explorer Deleted

### ISSUE THREAD

**Issue by InterstellarScout** [mmarcincin/HB-DRM-free-bulk-downloader#16]
I recently upgraded to windows 11. Woohoo!
Internet Explorer no longer exists. (Ref: https://www.theverge.com/2021/6/25/22550714/microsoft-windows-11-internet-explorer-disabled) 

How can we log into humble bundle without it to use this script?

**Comment by mmarcincin** [comment]
I'll look into it, atm the script relies on existing credentials in your ie instance so it most likely won't work for now.

**Comment by mmarcincin** [comment]
I updated the script to version 0.4.0, it works without Internet Explorer now. Let me know if it works for you now.
