### ISSUE TITLE
"Download stuck at the beginning" no matter what I do

### ISSUE THREAD

**Issue by jhall39** [mmarcincin/HB-DRM-free-bulk-downloader#17]
The script gives me the above error and the bundle information doesn't appear if I view the bundle page in IE even after making the changes you suggest in the readme. Maybe they changed the website since the last time it was updated?

**Comment by mmarcincin** [comment]
The website was changed some time ago (I changed my humble bundle tools javascript to reflect that) but it was still loading as old design in IE so it still worked. I tried to tinker with it a little bit and it looks like the new design is permanent now.
You can find that out by hovering above top links like bundles/choice, it has underline effect when you hover over them in new design.

It looks like the IE really reached the end of life for humblebundle website even before Win11.
I'll try to make it work in current state but I am not sure if I'll be successful.

Script will need rework for Microsoft Edge automation anyway when going forward (Win11 support).

**Comment by mmarcincin** [comment]
I updated the script to version 0.4.0, it works without Internet Explorer now. Let me know if it works for you now.
