### ISSUE TITLE
Multiple Links Error

### ISSUE THREAD

**Issue by GiuseppeChillemi** [mmarcincin/HB-DRM-free-bulk-downloader#5]
If you download multiple bundles you get errors for all the subsequent but the first one:

link: https://www.humblebundle.com/downloads?key=X262F**********
preferred labels: none
strict mode: disabled
OS: default
Eccezione da HRESULT: 0x800A01B6
In E:\HB-DRM-free-bulk-downloader-master\HB-DRM-Free_download.ps1:99 car:10
+ ...      while (($ie.Document.getElementsByClassName("whitebox-redux").le ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException

Eccezione da HRESULT: 0x800A01B6
In E:\HB-DRM-free-bulk-downloader-master\HB-DRM-Free_download.ps1:109 car:3
+         $docTitle = $doc.getElementsByTagName("title")[0].innerText.t ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException

==============================================================
2 / 19 - Humble Book Bundle_ World Foods by Lonely Planet
https://www.humblebundle.com/downloads?key=X262Frx************
--------------------------------------------------------------
Eccezione da HRESULT: 0x800A01B6
In E:\HB-DRM-free-bulk-downloader-master\HB-DRM-Free_download.ps1:146 car:3
+         $hb = $doc.getElementsByClassName("icn")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException

**Comment by mmarcincin** [comment]
Try the steps from the other comment:
https://github.com/mmarcincin/HB-DRM-free-bulk-downloader/issues/6#issuecomment-538516847
