### ISSUE TITLE
Trailing Whitespace in Book Titles

### ISSUE THREAD

**Issue by ratinoxone** [mmarcincin/HB-DRM-free-bulk-downloader#7]
When a book title has trailing whitespace  in the name for example

> Humble Books Bundle_ Neil Gaiman Rarities\Adventures in the Dream Trade \

the download directory is created with the trailing spaces which causes errors in Explorer (invalid file name) and the downloader

> New-Item : An item with the specified name \\?\E:\Documents\Humble Bundle\downloads\Humble Books Bundle_ Neil Gaiman Rarities\Adventures in the Dream Trade  already exists.

Suggested fix: remove leading and trailing whitespace from collection and title names before any processing.

**Comment by mmarcincin** [comment]
Sorry for late reply.
I'll update it in version 0.3.5. Let me know if it works correctly afterwards.
Thanks for feedback :).
